---
title: "Syllabus"
editor: source
format:
  html: 
    code-fold: true
    html-math-method: katex
---

## Math 201: Elementary Statistics

### Course Information

**Term:** Fall 2023

**Instructor:** Isaac Quintanilla Salinas

**Contact:** isaac.qs\@csuci.edu

**Office Location:** BTE 2840

**Office Hours:**

| OH       | Course       | R Programming | Math/Stat Hour |
|:---------|:-------------|:--------------|:---------------|
| Day      | MW           | Tue           | Tue            |
| Location | BTE 2840     | BTE 2810      | BTE 2810       |
| Time     | 4:30-5:30 PM | 10-12 AM      | 4-6 PM         |

Or by Zoom appointment.

**Lecture:** Monday and Wednesday 3:00-4:15 PM in BT 1462

### Course Description

Critical reasoning using a quantitative and statistical, problem-solving approach to solving real-world problems. Topics include: probability and statistics, sample data, probability and empirical data distributions, sampling techniques, estimation and hypothesis testing, ANOVA, and correlation and regression analysis. Students will use standard statistical software to analyze real-world and simulated data. GenEd: B4

### Learning Outcomes

-   Prepare students for advanced courses in data-management and statistics
-   Reason both inductively and deductively with quantitative information and data
-   Use statistical software for complex statistical analysis of real-world and simulated data
-   Empower students to apply computational and inferential thinking to address real-world problems
-   Write the results of a statistical study and draw conclusion in reports

### Textbook

This course will use Coursekata, a Canvas-embedded textbook with built-in R functionality.

### Recommended Software

For this course, we will use R and RStudio. You will have access to them online, but you may download and install them on your computer.

-   **R** is a free statistical software program that is available for download at: <https://www.r-project.org/>.

-   **RStudio** provides free and open source tools for your data analysis in R: <https://www.rstudio.com/>

### Course Grading

| Category            | Percentage |
|:--------------------|:-----------|
| Reading Assignments | 15%        |
| Lab Assignments     | 15%        |
| Weekly Quizzes      | 15%        |
| Pre-Test            | 5%         |
| Post-Test           | 5%         |
| Exam 1              | 15%        |
| Exam 2              | 15%        |
| Exam 3              | 15%        |

At the end of the quarter, course grades will be assigned according to the following scale:

|         |            |        |            |         |            |         |            |       |       |
|:--------|:-----------|:-------|:-----------|:--------|:-----------|:--------|:-----------|:------|:------|
| **A+**  | 98 -- 100  | **B+** | 87 -- \<90 | **C+**  | 77 -- \<80 | **D+**  | 67 -- \<70 |       |       |
| **A**   | 93 -- \<98 | **B**  | 83 -- \<87 | **C**   | 73 -- \<77 | **D**   | 63 -- \<67 | **F** | \< 60 |
| **A--** | 90 - \<93  | **B-** | 80 -- \<83 | **C--** | 70 -- \<73 | **D--** | 60 -- \<63 |       |       |

#### Lab Assignments

#### Reading Assignments

#### Exams

There will be three exams. Exam #1 will most likely be during the 6th week of the semester. Exam #2 will most likely be during the 12th week of the semester. Exam #3 will be on finals week. While the exams are not considered cumulative, the material builds on each other. Developing a strong understanding of the material through out the course is important for your success. At the end of the semester, your lowest exam grade will be replaced by your median average exam grade. This course will operate under a zero-tolerance policy. Talking during the time of the exam, sharing materials, looking at another students' exam, or not following directions given will be subject to the University's academic integrity policy.

#### Extra Credit

There will be **3** extra credit opportunities worth a total of 10% of your overall grade. (There are no make-ups for missed extra credit assignments!) More information will be provided on the extra credit assignments on a later date. Information on the extra credit can be found [here](ec.html).

### Class Schedule

The following outline may be subject to change. Any changes will be announced in class.

| Week        | Topic                                           | Ch. Due | Lab Due |
|:------------|:------------------------------------------------|:--------|:--------|
| 8/21-8/25   | Welcome to College/Course                       |         |         |
| 8/28-9/1    | Welcome to Statistics: A Modeling Approach      | Ch 1    |         |
| 9/4-9/8     | Understanding Data                              | Ch 2    |         |
| 9/11-9/15   | Examining Distributions                         | Ch 3    |         |
| 9/18-9/22   | Explaining Variation                            | Ch 4    |         |
| 9/25-9/29   | Exam #1/ A Simple Model                         |         |         |
| 10/2-10/6   | A Simple Model                                  | Ch 5    |         |
| 10/9-10/13  | Quantifying Error                               | Ch 6    |         |
| 10/16-10/20 | Adding an Explanatory Variable to the Model     | Ch 7    |         |
| 10/23-10/27 | Digging Deeper into Group Model                 | Ch 8    |         |
| 10/30-11/3  | Models with a Quantitative Explanatory Variable | Ch 9    |         |
| 11/6-11/10  | Exam #2                                         |         |         |
| 11/13-11/17 | Logic of Inference                              | Ch 10   |         |
| 11/20-11/24 | Model Comparison with F                         | Ch 11   |         |
| 11/27-12/1  | Parameter Estimation and Confidence Intervals   | Ch 12   |         |
| 12/4-12/8   | Exam #3                                         | Ch 13   |         |

### University Policies

1.  **Academic Honesty**:

    Please conduct yourself with honesty and integrity. Do not submit others' work as your own. For assignments and quizzes that allow you to work with a group, only put your name on what the group submits if you genuinely contributed to the work. Work completely independently on exams, using only the materials that are indicated as allowed. Failure to observe academic honesty results in substantial penalties that can include failing the course.

2.  **Disabilities:**

    If you are a student with a disability requesting reasonable accommodations in this course, you need to contact Disability Accommodations and Support Services (DASS) located on the second floor of Arroyo Hall, via email accommodations\@csuci.edu or call 805-437-3331. All requests for reasonable accommodations require registration with DASS in advance of need: <https://www.csuci.edu/dass/students/apply-for-services.htm>. Faculty, students and DASS will work together regarding classroom accommodations. You are encouraged to discuss approved.

3.  **Emergency Procedure Notice to Students:**

    CSUCI is following guidelines and public orders from the California Department of Public Health and Ventura County Public Health for the COVID-19 pandemic as it pertains to CSUCI students, employees and visitors on the campus. Students are expected to adhere to all health and safety requirements as noted on the University's Spring 2023 Semester [website](https://www.csuci.edu/news/campus-updates/covid-19/index.htm) or they may be subject to removal from the classroom.
