---
title: "Data Generating Process"
format:
  revealjs:
    scrollable: true
    theme: [default, styles.scss]
    navigation-mode: vertical
    controls-layout: bottom-right
    controls-tutorial: true
    incremental: false 
    chalkboard:
      src: notes/chalkboard_1a.json
      storage: chalkboard_pres
      theme: whiteboard
      chalk-width: 4
knitr:
  opts_chunk: 
    echo: false
    eval: true
    message: false
    warnings: false
    comment: "#>" 
    
revealjs-plugins:
  - pointer
  - verticator
  
filters: 
  - reveal-header
  - code-fullscreen
  - reveal-auto-agenda
  
auto-agenda:
  bullets: numbered
  heading: Learning Outcomes
  
editor: visual
---

```{r}
#| include: false

library(palmerpenguins)
library(ggformula)
library(ThemePark)
```

# Summary Statistics

## 

# Data Visualization

## Histogram

```{r}
penguins |> gf_histogram(~bill_length_mm, data = _) |> 
  gf_labs(title = "Histogram of Bill Length", x = "Bill Length (mm)") +
  theme_barbie()
```

## Box Plot

```{r}
penguins |> ggplot(aes(bill_length_mm)) +
  geom_boxplot() +
  ggtitle("Box Plot of Bill Length") +
  theme_futurama()
```

# Summarizing Categorical Variables
