---
title: "Summarizing Data"
format:
  revealjs:
    scrollable: true
    theme: [default, styles.scss]
    navigation-mode: vertical
    controls-layout: bottom-right
    controls-tutorial: true
    incremental: false 
    chalkboard:
      src: notes/chalkboard_1a.json
      storage: chalkboard_pres
      theme: whiteboard
      chalk-width: 4
knitr:
  opts_chunk: 
    echo: false
    eval: true
    message: false
    warnings: false
    comment: "#>" 
    
revealjs-plugins:
  - pointer
  - verticator
  
filters: 
  - reveal-header
  - code-fullscreen
  - reveal-auto-agenda
  
auto-agenda:
  bullets: numbered
  heading: Learning Outcomes
  
editor: visual
---

```{r}
#| include: false

library(palmerpenguins)
library(ggformula)
library(ThemePark)
```

# Announcements

# Summarizing Categorical Variables

## Categorical Variables

## Frequency Tables

## Proportional Tables

## Bar Charts

## Bar Charts R Code

```{r}
#| echo: true
#| eval: false

gf_bar(~species, data = penguins)

```

## Bar Charts R Code

```{r}
penguins |> gf_bar(~species) + theme_zelda()
  
```

# Explaining Variation
